routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');







Route::resource('dokters', 'DoktersController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('pendaftarans', 'PendaftaransController');

Route::resource('pasiens', 'PasiensController');

Route::resource('pemeriksaans', 'PemeriksaanController');

Route::resource('jenisHewans', 'Jenis_hewansController');

Route::resource('transakses', 'TransaksisController');

Route::resource('satuans', 'SatuansController');

Route::resource('obats', 'ObatsController');



Route::resource('rekamMediks', 'RekamMedikController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('laporans', 'LaporanController');

Route::get('laporan_jasa_dokter','PemeriksaanController@laporanJasaDokter');

resources/views/transakses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaksis
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'transakses.store']) !!}

                        @include('transakses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transakses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaksis
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($transaksis, ['route' => ['transakses.update', $transaksis->id], 'method' => 'patch']) !!}

                        @include('transakses.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/transakses/fields.blade.php
<!-- Anamnese Field -->
<div class="form-group col-sm-6">
    {!! Form::label('anamnese', 'Anamnese:') !!}
    {!! Form::text('anamnese', null, ['class' => 'form-control']) !!}
</div>

<!-- Pemberian Obat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pemberian_obat', 'Pemberian Obat:') !!}
    {!! Form::text('pemberian_obat', null, ['class' => 'form-control']) !!}
</div>

<!-- Dosis Field -->
<div class="form-group col-sm-6">
    {!! Form::label('dosis', 'Dosis:') !!}
    {!! Form::text('dosis', null, ['class' => 'form-control']) !!}
</div>

<!-- Tarif Jasa Dokter Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tarif_jasa_dokter', 'Tarif Jasa Dokter:') !!}
    {!! Form::text('tarif_jasa_dokter', null, ['class' => 'form-control']) !!}
</div>

<!-- Pasien Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pasien_id', 'Pasien Id:') !!}
    {!! Form::select('pasien_id',$pasien, null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('transakses.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/transakses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Transakses</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('transakses.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('transakses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/transakses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Transaksis
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('transakses.show_fields')
                    <a href="{!! route('transakses.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/transakses/show_fields.blade.php
<!-- Anamnese Field -->
<div class="form-group">
    {!! Form::label('anamnese', 'Anamnese:') !!}
    <p>{!! $transaksis->anamnese !!}</p>
</div>

<!-- Pemberian Obat Field -->
<div class="form-group">
    {!! Form::label('pemberian_obat', 'Pemberian Obat:') !!}
    <p>{!! $transaksis->pemberian_obat !!}</p>
</div>

<!-- Dosis Field -->
<div class="form-group">
    {!! Form::label('dosis', 'Dosis:') !!}
    <p>{!! $transaksis->dosis !!}</p>
</div>

<!-- Tarif Jasa Dokter Field -->
<div class="form-group">
    {!! Form::label('tarif_jasa_dokter', 'Tarif Jasa Dokter:') !!}
    <p>{!! $transaksis->tarif_jasa_dokter !!}</p>
</div>

<!-- Pasien Id Field -->
<div class="form-group">
    {!! Form::label('pasien_id', 'Pasien Id:') !!}
    <p>{!! $transaksis->pasien_id !!}</p>
</div>

resources/views/transakses/table.blade.php
<div class="table-responsive">
    <table class="table" id="transakses-table">
        <thead>
            <tr>
                <th>Anamnese</th>
        <th>Pemberian Obat</th>
        <th>Dosis</th>
        <th>Tarif Jasa Dokter</th>
        <th>Pasien Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($transakses as $transaksis)
            <tr>
                <td>{!! $transaksis->anamnese !!}</td>
            <td>{!! $transaksis->pemberian_obat !!}</td>
            <td>{!! $transaksis->dosis !!}</td>
            <td>{!! $transaksis->tarif_jasa_dokter !!}</td>
            <td>{!! $transaksis->pasien_id !!}</td>
                <td>
                    {!! Form::open(['route' => ['transakses.destroy', $transaksis->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('transakses.show', [$transaksis->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('transakses.edit', [$transaksis->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>