routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');







Route::resource('dokters', 'DoktersController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('pendaftarans', 'PendaftaransController');

Route::resource('pasiens', 'PasiensController');

Route::resource('pemeriksaans', 'PemeriksaanController');

Route::resource('jenisHewans', 'Jenis_hewansController');

Route::resource('transakses', 'TransaksisController');

Route::resource('satuans', 'SatuansController');

Route::resource('obats', 'ObatsController');



Route::resource('rekamMediks', 'RekamMedikController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('laporans', 'LaporanController');

Route::get('laporan_jasa_dokter','PemeriksaanController@laporanJasaDokter');

app/Models/Jenis_hewans.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Jenis_hewans
 * @package App\Models
 * @version December 21, 2019, 1:55 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection pasiens
 * @property string jenis_hewan
 */
class Jenis_hewans extends Model
{
    use SoftDeletes;

    public $table = 'jenis_hewan';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'jenis_hewan'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'jenis_hewan' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function pasiens()
    {
        return $this->hasMany(\App\Models\Pasien::class, 'jenis_hewan_id');
    }
}

app/Http/Controllers/Jenis_hewansController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateJenis_hewansRequest;
use App\Http\Requests\UpdateJenis_hewansRequest;
use App\Repositories\Jenis_hewansRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class Jenis_hewansController extends AppBaseController
{
    /** @var  Jenis_hewansRepository */
    private $jenisHewansRepository;

    public function __construct(Jenis_hewansRepository $jenisHewansRepo)
    {
        $this->jenisHewansRepository = $jenisHewansRepo;
    }

    /**
     * Display a listing of the Jenis_hewans.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $jenisHewans = $this->jenisHewansRepository->all();

        return view('jenis_hewans.index')
            ->with('jenisHewans', $jenisHewans);
    }

    /**
     * Show the form for creating a new Jenis_hewans.
     *
     * @return Response
     */
    public function create()
    {
        return view('jenis_hewans.create');
    }

    /**
     * Store a newly created Jenis_hewans in storage.
     *
     * @param CreateJenis_hewansRequest $request
     *
     * @return Response
     */
    public function store(CreateJenis_hewansRequest $request)
    {
        $input = $request->all();

        $jenisHewans = $this->jenisHewansRepository->create($input);

        Flash::success('Jenis Hewans saved successfully.');

        return redirect(route('jenisHewans.index'));
    }

    /**
     * Display the specified Jenis_hewans.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $jenisHewans = $this->jenisHewansRepository->find($id);

        if (empty($jenisHewans)) {
            Flash::error('Jenis Hewans not found');

            return redirect(route('jenisHewans.index'));
        }

        return view('jenis_hewans.show')->with('jenisHewans', $jenisHewans);
    }

    /**
     * Show the form for editing the specified Jenis_hewans.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $jenisHewans = $this->jenisHewansRepository->find($id);

        if (empty($jenisHewans)) {
            Flash::error('Jenis Hewans not found');

            return redirect(route('jenisHewans.index'));
        }

        return view('jenis_hewans.edit')->with('jenisHewans', $jenisHewans);
    }

    /**
     * Update the specified Jenis_hewans in storage.
     *
     * @param int $id
     * @param UpdateJenis_hewansRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateJenis_hewansRequest $request)
    {
        $jenisHewans = $this->jenisHewansRepository->find($id);

        if (empty($jenisHewans)) {
            Flash::error('Jenis Hewans not found');

            return redirect(route('jenisHewans.index'));
        }

        $jenisHewans = $this->jenisHewansRepository->update($request->all(), $id);

        Flash::success('Jenis Hewans updated successfully.');

        return redirect(route('jenisHewans.index'));
    }

    /**
     * Remove the specified Jenis_hewans from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $jenisHewans = $this->jenisHewansRepository->find($id);

        if (empty($jenisHewans)) {
            Flash::error('Jenis Hewans not found');

            return redirect(route('jenisHewans.index'));
        }

        $this->jenisHewansRepository->delete($id);

        Flash::success('Jenis Hewans deleted successfully.');

        return redirect(route('jenisHewans.index'));
    }
}

resources/views/jenis_hewans/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Jenis Hewans
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'jenisHewans.store']) !!}

                        @include('jenis_hewans.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jenis_hewans/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Jenis Hewans
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($jenisHewans, ['route' => ['jenisHewans.update', $jenisHewans->id], 'method' => 'patch']) !!}

                        @include('jenis_hewans.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/jenis_hewans/fields.blade.php
<!-- Jenis Hewan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('jenis_hewan', 'Jenis Hewan:') !!}
    {!! Form::text('jenis_hewan', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('jenisHewans.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/jenis_hewans/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Jenis Hewans</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('jenisHewans.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('jenis_hewans.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/jenis_hewans/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Jenis Hewans
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('jenis_hewans.show_fields')
                    <a href="{!! route('jenisHewans.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/jenis_hewans/show_fields.blade.php
<!-- Jenis Hewan Field -->
<div class="form-group">
    {!! Form::label('jenis_hewan', 'Jenis Hewan:') !!}
    <p>{!! $jenisHewans->jenis_hewan !!}</p>
</div>

resources/views/jenis_hewans/table.blade.php
<div class="table-responsive">
    <table class="table" id="jenisHewans-table">
        <thead>
            <tr>
                <th>Jenis Hewan</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($jenisHewans as $jenisHewans)
            <tr>
                <td>{!! $jenisHewans->jenis_hewan !!}</td>
                <td>
                    {!! Form::open(['route' => ['jenisHewans.destroy', $jenisHewans->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('jenisHewans.show', [$jenisHewans->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('jenisHewans.edit', [$jenisHewans->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>