routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');







Route::resource('dokters', 'DoktersController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('pendaftarans', 'PendaftaransController');

Route::resource('pasiens', 'PasiensController');

Route::resource('pemeriksaans', 'PemeriksaanController');

Route::resource('jenisHewans', 'Jenis_hewansController');

Route::resource('transakses', 'TransaksisController');

Route::resource('satuans', 'SatuansController');

Route::resource('obats', 'ObatsController');



Route::resource('rekamMediks', 'RekamMedikController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('pemiliks', 'PemiliksController');

Route::resource('laporans', 'LaporanController');

Route::get('laporan_jasa_dokter','PemeriksaanController@laporanJasaDokter');

resources/views/rekam_mediks/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rekam Medik
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'rekamMediks.store']) !!}

                        @include('rekam_mediks.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rekam_mediks/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rekam Medik
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($rekamMedik, ['route' => ['rekamMediks.update', $rekamMedik->id], 'method' => 'patch']) !!}

                        @include('rekam_mediks.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/rekam_mediks/fields.blade.php
<!-- Pasien Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pasien_id', 'Pasien Id:') !!}
    {!! Form::select('pasien_id',$pasien, null, ['class' => 'form-control']) !!}
</div>

<!-- Diagnosa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('diagnosa', 'Diagnosa:') !!}
    {!! Form::text('diagnosa', null, ['class' => 'form-control']) !!}
</div>

<!-- Dokter Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('dokter_id', 'Dokter Id:') !!}
    {!! Form::select('dokter_id',$dokter, null, ['class' => 'form-control']) !!}
</div>

<!-- Tgl Pemeriksaan Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tgl_pemeriksaan', 'Tgl Pemeriksaan:') !!}
    {!! Form::date('tgl_pemeriksaan', null, ['class' => 'form-control','id'=>'tgl_pemeriksaan']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#tgl_pemeriksaan').datetimepicker({
            format: 'YYYY-MM-DD',
        })
    </script>
@endsection

<!-- Pemeriksaan Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pemeriksaan_id', 'Pemeriksaan Id:') !!}
    {!! Form::number('pemeriksaan_id',null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('rekamMediks.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/rekam_mediks/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Rekam Mediks</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('rekamMediks.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('rekam_mediks.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/rekam_mediks/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Rekam Medik
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('rekam_mediks.show_fields')
                    <a href="{!! route('rekamMediks.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/rekam_mediks/show_fields.blade.php
<!-- Pasien Id Field -->
<div class="form-group">
    {!! Form::label('pasien_id', 'Pasien Id:') !!}
    <p>{!! $rekamMedik->pasien_id !!}</p>
</div>

<!-- Diagnosa Field -->
<div class="form-group">
    {!! Form::label('diagnosa', 'Diagnosa:') !!}
    <p>{!! $rekamMedik->diagnosa !!}</p>
</div>

<!-- Dokter Id Field -->
<div class="form-group">
    {!! Form::label('dokter_id', 'Dokter Id:') !!}
    <p>{!! $rekamMedik->dokter_id !!}</p>
</div>

<!-- Tgl Pemeriksaan Field -->
<div class="form-group">
    {!! Form::label('tgl_pemeriksaan', 'Tgl Pemeriksaan:') !!}
    <p>{!! $rekamMedik->tgl_pemeriksaan !!}</p>
</div>

<!-- Pemeriksaan Id Field -->
<div class="form-group">
    {!! Form::label('pemeriksaan_id', 'Pemeriksaan Id:') !!}
    <p>{!! $rekamMedik->pemeriksaan_id !!}</p>
</div>

resources/views/rekam_mediks/table.blade.php
<div class="table-responsive">
    <table class="table" id="rekamMediks-table">
        <thead>
            <tr>
                <th>Pasien Id</th>
        <th>Diagnosa</th>
        <th>Dokter Id</th>
        <th>Tgl Pemeriksaan</th>
        <th>Pemeriksaan Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($rekamMediks as $rekamMedik)
            <tr>
                <td>{!! $rekamMedik->pasien_id !!}</td>
            <td>{!! $rekamMedik->diagnosa !!}</td>
            <td>{!! $rekamMedik->dokter_id !!}</td>
            <td>{!! $rekamMedik->tgl_pemeriksaan !!}</td>
            <td>{!! $rekamMedik->pemeriksaan_id !!}</td>
                <td>
                    {!! Form::open(['route' => ['rekamMediks.destroy', $rekamMedik->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('rekamMediks.show', [$rekamMedik->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('rekamMediks.edit', [$rekamMedik->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>